# Update dependencies

version: 2
updates:
# Update the Github Action  versions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  - "automerge"
version: 2
updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  allow:
    - dependency-name: "src"
  schedule:
    interval: "daily"
  - "dependencies"
  - "automerge"
